# Phase K Wave 5 — Apone (DevOps).
#
# Module outputs. The names follow the convention
# `<resource>_<attribute>` so downstream operators / wrapper
# modules can grep by the resource they're interested in.
#
# Sensitive outputs (DB password, KMS key IDs) are marked
# `sensitive = true` so `terraform plan` / `terraform apply`
# logs do not leak the value. Operators retrieve them via
# `terraform output -raw <name>`.

output "vpc_id" {
  description = "VPC ID."
  value       = aws_vpc.this.id
}

output "vpc_cidr" {
  description = "VPC CIDR block."
  value       = aws_vpc.this.cidr_block
}

output "public_subnet_ids" {
  description = "Public subnet IDs (3 — one per AZ)."
  value       = aws_subnet.public[*].id
}

output "private_subnet_ids" {
  description = "Private subnet IDs (3 — one per AZ)."
  value       = aws_subnet.private[*].id
}

# ── EKS ────────────────────────────────────────────────────────────

output "cluster_name" {
  description = "EKS cluster name."
  value       = aws_eks_cluster.this.name
}

output "cluster_endpoint" {
  description = "EKS API server endpoint (URL)."
  value       = aws_eks_cluster.this.endpoint
}

output "cluster_certificate_authority_data" {
  description = "EKS cluster CA cert (base64). Pass to kubeconfig builders."
  value       = aws_eks_cluster.this.certificate_authority[0].data
  sensitive   = true
}

output "cluster_oidc_issuer_url" {
  description = "EKS OIDC issuer URL — pass to IRSA / GitHub-Actions OIDC trust policies for cross-cluster IAM federation. THIS IS THE OUTPUT THE PROD-DEPLOY WORKFLOW CONSUMES."
  value       = aws_eks_cluster.this.identity[0].oidc[0].issuer
}

output "cluster_oidc_provider_arn" {
  description = "ARN of the IAM OIDC provider for IRSA."
  value       = aws_iam_openid_connect_provider.cluster.arn
}

output "node_group_role_arn" {
  description = "IAM role ARN attached to the default managed node group."
  value       = aws_iam_role.node.arn
}

# ── RDS ────────────────────────────────────────────────────────────

output "db_endpoint" {
  description = "RDS Postgres endpoint (host:port). Pass to ConnectionStrings__PostgreSql."
  value       = aws_db_instance.this.endpoint
}

output "db_instance_arn" {
  description = "RDS Postgres instance ARN. Consumed by the DR env (`envs/dr-us-west-2/`) via `terraform_remote_state` to set up the cross-region read replica's `replicate_source_db`."
  value       = aws_db_instance.this.arn
}

output "db_kms_key_arn" {
  description = "ARN of the customer-managed KMS key encrypting the primary RDS storage. Surfaced for audit (DR replicas use a SECONDARY-region KMS key — AWS forbids cross-region CMK sharing — but the primary's key ARN is logged in the DR module's tags)."
  value       = aws_kms_key.rds.arn
}

output "db_address" {
  description = "RDS Postgres host only (no port). Often handier than db_endpoint when composing connection strings."
  value       = aws_db_instance.this.address
}

output "db_port" {
  description = "RDS Postgres port."
  value       = aws_db_instance.this.port
}

output "db_name" {
  description = "Initial database name created by RDS."
  value       = aws_db_instance.this.db_name
}

output "db_master_username" {
  description = "RDS master username (non-sensitive; the password is the secret)."
  value       = aws_db_instance.this.username
}

output "db_master_password" {
  description = "RDS master password — generated by terraform. Seed into SSM ParameterStore (canonical path: /mahjong/$${environment}/db/master_password) immediately after first apply; subsequent rotations should be done via the RDS console + an SSM put-parameter call, NOT by re-applying terraform (the lifecycle.ignore_changes = [password] block prevents drift)."
  value       = random_password.db_master.result
  sensitive   = true
}

# ── ECR ────────────────────────────────────────────────────────────

output "ecr_repository_url" {
  description = "ECR repository URL — push images here (after `aws ecr get-login-password`)."
  value       = aws_ecr_repository.mahjong.repository_url
}

output "ecr_repository_arn" {
  description = "ECR repository ARN."
  value       = aws_ecr_repository.mahjong.arn
}

# ── GitHub OIDC deploy role ──────────────────────────────────────

output "github_deploy_role_arn" {
  description = "IAM role ARN that GitHub Actions workflows assume via OIDC. Configure as the `role-to-assume` input to aws-actions/configure-aws-credentials in CI."
  value       = aws_iam_role.github_deploy.arn
}

output "github_oidc_provider_arn" {
  description = "ARN of the GitHub-Actions OIDC provider in this account."
  value       = aws_iam_openid_connect_provider.github.arn
}

# ── kubeconfig helper ────────────────────────────────────────────

output "kubeconfig_update_command" {
  description = "Run this to bind a local kubeconfig context to the new cluster: `aws eks update-kubeconfig …`."
  value       = "aws eks update-kubeconfig --region ${var.region} --name ${aws_eks_cluster.this.name} --alias ${aws_eks_cluster.this.name}"
}
