# Phase K Wave 5 — Apone (DevOps).
#
# Variable surface for the bootstrap module. Sensible defaults for
# the staging shape; per-environment tfvars override.

variable "environment" {
  description = "Environment name (staging, prod, dr-us-west-2, etc.). Drives resource tags + lifecycle decisions (multi-AZ, deletion protection)."
  type        = string

  validation {
    condition     = can(regex("^[a-z][a-z0-9-]{1,30}$", var.environment))
    error_message = "environment must be lower-case alphanumeric + hyphen, 2-31 chars (matches the tag-value regex AWS enforces on resources)."
  }
}

variable "region" {
  description = "AWS region. Defaults to us-east-1 for the cheapest cross-AZ traffic floor; pick us-west-2 for DR."
  type        = string
  default     = "us-east-1"
}

variable "vpc_cidr" {
  description = "VPC CIDR block. /16 is the only supported size — the CIDR-split logic in main.tf assumes 16 bits of room for subnets."
  type        = string
  default     = "10.0.0.0/16"

  validation {
    condition     = can(cidrhost(var.vpc_cidr, 0)) && substr(var.vpc_cidr, length(var.vpc_cidr) - 3, 3) == "/16"
    error_message = "vpc_cidr must be a valid /16 CIDR (e.g. 10.0.0.0/16)."
  }
}

# ── EKS ────────────────────────────────────────────────────────────

variable "cluster_name" {
  description = "EKS cluster name. Defaults to mahjong-$${environment}; override only if you need to clash-avoid in a shared account."
  type        = string
  default     = ""
}

variable "kubernetes_version" {
  description = "EKS Kubernetes version. Track AWS's '12 months of support' window; bump in the next wave if AWS deprecates the current one."
  type        = string
  default     = "1.30"
}

variable "node_instance_types" {
  description = "EKS managed-node-group instance types. List of equivalent types so Spot fallback works (Spot uses the first available)."
  type        = list(string)
  default     = ["t3.medium", "t3a.medium"]
}

variable "node_desired_size" {
  description = "EKS managed-node-group desired size. 3 is the cheapest HA floor (one per AZ)."
  type        = number
  default     = 3
}

variable "node_min_size" {
  description = "EKS managed-node-group minimum. Must be >= 1 so the cluster doesn't scale to zero on a quiet day."
  type        = number
  default     = 2
}

variable "node_max_size" {
  description = "EKS managed-node-group maximum. 10 supports a 3× headroom over the default replicas=3."
  type        = number
  default     = 10
}

variable "node_disk_size_gb" {
  description = "EKS node EBS volume size (GB). Cluster bin-pack heuristics need ~30 GB minimum for kubelet + image cache + ephemeral writes."
  type        = number
  default     = 50
}

variable "cluster_public_access" {
  description = "Whether the EKS API server is reachable from the public internet. true for the bootstrap (CI must reach it); flip to false + private-only once a bastion / Tailscale exists."
  type        = bool
  default     = true
}

# ── RDS ────────────────────────────────────────────────────────────

variable "db_instance_class" {
  description = "RDS Postgres instance class. db.t4g.small is the cheapest credit-bursty option that supports gp3 storage; jump to db.m6g.large for sustained prod load."
  type        = string
  default     = "db.t4g.small"
}

variable "db_engine_version" {
  description = "Postgres engine version. Pin a minor; major bumps are coordinated DB-migration events."
  type        = string
  default     = "16.4"
}

variable "db_allocated_storage_gb" {
  description = "Initial Postgres storage. RDS auto-scales up to db_max_allocated_storage_gb when the volume fills."
  type        = number
  default     = 20
}

variable "db_max_allocated_storage_gb" {
  description = "RDS storage auto-scaling ceiling. Set higher than expected steady-state so a runaway INSERT doesn't ENOSPC."
  type        = number
  default     = 100
}

variable "db_multi_az" {
  description = "Whether the RDS instance is multi-AZ. true for prod (standby + failover); false for staging / DR-warm to save cost."
  type        = bool
  default     = false
}

variable "db_deletion_protection" {
  description = "RDS deletion protection. Always true for prod; false for staging / DR to allow `terraform destroy` tear-downs."
  type        = bool
  default     = false
}

variable "db_name" {
  description = "Initial database name created by RDS."
  type        = string
  default     = "mahjong"
}

variable "db_master_username" {
  description = "RDS master username. The password is generated by terraform (random_password) and surfaced as a sensitive output for ESO seeding."
  type        = string
  default     = "mahjong_app"
}

variable "db_backup_retention_days" {
  description = "Number of days to retain automated RDS backups. 7 is the prod floor; 1 is the staging floor."
  type        = number
  default     = 7
}

# ── ECR ────────────────────────────────────────────────────────────

variable "ecr_repository_name" {
  description = "ECR repository name. Defaults to mahjong-autotable; override only if mirroring to a non-canonical name."
  type        = string
  default     = "mahjong-autotable"
}

variable "ecr_keep_last_n_images" {
  description = "ECR lifecycle policy — number of recent tagged images to retain. 30 covers ~3 months of weekly tag pushes."
  type        = number
  default     = 30
}

# ── GitHub OIDC ────────────────────────────────────────────────────

variable "github_org" {
  description = "GitHub organisation or user owning the repo. The OIDC trust policy is scoped to {org}/{repo}."
  type        = string
  default     = "long2know"
}

variable "github_repo" {
  description = "GitHub repository name (without the org prefix)."
  type        = string
  default     = "mahjong-autotable"
}

variable "github_oidc_subjects" {
  description = "OIDC subject claim patterns allowed to assume the deploy role. Default scopes to main branch + v* tags; expand for environment-named refs as needed."
  type        = list(string)
  default = [
    "repo:long2know/mahjong-autotable:ref:refs/heads/main",
    "repo:long2know/mahjong-autotable:ref:refs/tags/v*",
  ]
}
