#!/usr/bin/env bash
# Phase J Wave 8 (Apone) — generate a local .env.dev with strong random
# values for every credential the backend / docker-compose needs.
#
# Idempotent: refuses to overwrite an existing .env.dev. Delete it
# manually if you want to regenerate.
#
# Usage:
#   ./scripts/generate-dev-secrets.sh            # writes ./.env.dev
#   ./scripts/generate-dev-secrets.sh path/to/.env  # custom destination
#
# Format: docker-compose / dotnet both read env vars; the file uses
# .NET's double-underscore convention so the same file works for
# `docker compose --env-file .env.dev` and `set -a; source .env.dev; set +a`.

set -euo pipefail

OUT="${1:-.env.dev}"

if [[ -e "$OUT" ]]; then
    echo "refusing to overwrite existing $OUT" >&2
    echo "(delete it first if you really want to regenerate)" >&2
    exit 1
fi

# openssl is in the base image; fall back to /dev/urandom if not.
gen_b64() {
    local bytes="${1:-48}"
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -base64 "$bytes" | tr -d '\n'
    else
        head -c "$bytes" /dev/urandom | base64 | tr -d '\n'
    fi
}

PG_PASS="$(gen_b64 24 | tr -d '/+=' | head -c 32)"
JWT_KEY="$(gen_b64 64)"
COOKIE_KEY="$(gen_b64 64)"

umask 077
cat > "$OUT" <<EOF
# Generated by scripts/generate-dev-secrets.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT COMMIT — this file is in .gitignore via the .env* pattern.

# --- Backend env ---
ASPNETCORE_ENVIRONMENT=Development
ASPNETCORE_URLS=http://+:8080

# Persistence
Persistence__Provider=Sqlite
ConnectionStrings__Sqlite=Data Source=data/mahjong-autotable.dev.db
ConnectionStrings__PostgreSql=Host=localhost;Port=5432;Database=mahjong_autotable;Username=mahjong;Password=${PG_PASS}

# Auth (Wave 8 — Bishop). JWT_SIGNING_KEY feeds docker-compose.yml's
# \${JWT_SIGNING_KEY} substitution (injected as Authentication__JwtSigningKeys__0);
# Auth__JwtSigningKey is the direct container env for the `source .env.dev;
# dotnet run` path. Same value so both paths agree.
JWT_SIGNING_KEY=${JWT_KEY}
Auth__JwtSigningKey=${JWT_KEY}
Auth__CookieEncryptionKey=${COOKIE_KEY}

# Sentry (Wave 8 — Apone). Leave empty for a no-op SDK in dev.
Sentry__Dsn=
Sentry__Environment=Development
Sentry__SampleRate=1.0
Sentry__TracesSampleRate=0.0

# Build identifier — picked up by /health and /metrics
BUILD_SHA=$(git -C "$(dirname "$(readlink -f "$0")")/.." rev-parse --short HEAD 2>/dev/null || echo local)
EOF

echo "wrote $OUT (chmod 600)"
echo
echo "Quick start:"
echo "  source \"$OUT\""
echo "  cd src/backend && dotnet run --project src/Mahjong.Autotable.Api"
echo
echo "Compose (reads JWT_SIGNING_KEY + other vars from this file):"
echo "  docker compose --env-file \"$OUT\" up -d --build"
